app/src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("reviews.urls")),
    path("affidavits/", include("affidavits.urls")),
    path("book_records/", include("book_records.urls")),
    path("users/", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/affidavits/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
import random
import string

from django.db import models
from django.shortcuts import reverse
from django.utils.text import slugify
from users.models import User


class Affidavits(models.Model):
    id = models.IntegerField(
        db_column="ID", blank=True, primary_key=True
    )  # Field name made lowercase.
    date_received = models.TextField(
        db_column="DATE RECEIVED", blank=True, null=True
    )  # Field name made lowercase. Field renamed to remove unsuitable characters.
    date_required = models.TextField(
        db_column="DATE REQUIRED", blank=True, null=True
    )  # Field name made lowercase. Field renamed to remove unsuitable characters.
    officer_name = models.TextField(
        db_column="OFFICER NAME", blank=True, null=True
    )  # Field name made lowercase. Field renamed to remove unsuitable characters.
    contact_number = models.TextField(
        db_column="CONTACT NUMBER", blank=True, null=True
    )  # Field name made lowercase. Field renamed to remove unsuitable characters.
    licence_name = models.TextField(
        db_column="LICENCE NAME", blank=True, null=True
    )  # Field name made lowercase. Field renamed to remove unsuitable characters.
    dob = models.TextField(
        db_column="DOB", blank=True, null=True
    )  # Field name made lowercase.
    adress = models.TextField(
        db_column="ADRESS", blank=True, null=True
    )  # Field name made lowercase.
    vehicle_number = models.TextField(
        db_column="VEHICLE NUMBER", blank=True, null=True
    )  # Field name made lowercase. Field renamed to remove unsuitable characters.
    vehicle_owner = models.TextField(
        db_column="VEHICLE OWNER", blank=True, null=True
    )  # Field name made lowercase. Field renamed to remove unsuitable characters.
    mand = models.TextField(
        db_column="MAND", blank=True, null=True
    )  # Field name made lowercase.
    colour = models.TextField(
        db_column="COLOUR", blank=True, null=True
    )  # Field name made lowercase.
    chassis_number = models.TextField(
        db_column="CHASSIS NUMBER", blank=True, null=True
    )  # Field name made lowercase. Field renamed to remove unsuitable characters.
    engine_number = models.TextField(
        db_column="ENGINE NUMBER", blank=True, null=True
    )  # Field name made lowercase. Field renamed to remove unsuitable characters.
    status = models.TextField(
        db_column="STATUS", blank=True, null=True
    )  # Field name made lowercase.
    status_date = models.TextField(
        db_column="STATUS DATE", blank=True, null=True
    )  # Field name made lowercase. Field renamed to remove unsuitable characters.
    comments = models.TextField(
        db_column="COMMENTS", blank=True, null=True
    )  # Field name made lowercase.
    licence_number = models.TextField(
        db_column="LICENCE NUMBER", blank=True, null=True
    )  # Field name made lowercase. Field renamed to remove unsuitable characters.
    attachment = models.IntegerField(
        db_column="ATTACHMENT", blank=True, null=True
    )  # Field name made lowercase.
    type_requested = models.IntegerField(
        db_column="TYPE REQUESTED", blank=True, null=True
    )  # Field name made lowercase. Field renamed to remove unsuitable characters.

    class Meta:
        managed = False
        db_table = "affidavits"


class RequestType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name.title()


def generate_short_id():
    length = 8  # You can adjust the length as needed
    characters = string.ascii_letters + string.digits
    return "".join(random.choice(characters) for i in range(length)).upper()


class AffidavitNew(models.Model):
    affidavit_id = models.CharField(
        default=generate_short_id, editable=False, unique=True, max_length=8
    )
    slug = models.SlugField(max_length=255, unique=True, blank=True, null=True)
    date_received = models.DateField()
    date_required = models.DateField()
    officer_name = models.CharField(max_length=255)
    contact_number = models.CharField(max_length=255)
    request_type = models.ForeignKey(
        RequestType,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="affidavit_request_types",
    )
    licence_name = models.CharField(max_length=255, blank=True)
    licence_number = models.CharField(max_length=255, blank=True)
    dob = models.DateField("D.O.B", blank=True)
    address = models.TextField()
    vehicle_owner = models.CharField(max_length=255, blank=True)
    vehicle_number = models.CharField(max_length=255, blank=True)
    maker = models.CharField(max_length=255, blank=True)
    chassis_number = models.CharField(max_length=255, blank=True)
    engine_number = models.CharField(max_length=255, blank=True)
    colour = models.CharField(max_length=255, blank=True)
    comments = models.TextField(blank=True)
    attachment = models.FileField(blank=True, upload_to="affidavit_new/")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="affidavit_new_created_by"
    )
    updated_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="affidavit_new_updated_by"
    )
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.affidavit_id)
        super(AffidavitNew, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("affidavit-new-detail", kwargs={"slug": self.slug})

    def __str__(self):
        return f"{self.affidavit_id}"


class Status(models.Model):
    affidavit = models.ForeignKey(
        AffidavitNew, on_delete=models.CASCADE, related_name="statuses"
    )
    status = models.CharField(max_length=255)
    date = models.DateField()
    comments = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="status_created_by"
    )
    updated_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="status_updated_by"
    )

    def __str__(self):
        return f"{self.affidavit.affidavit_id} {self.status}"


class Comment(models.Model):
    affidavit = models.ForeignKey(
        AffidavitNew, on_delete=models.CASCADE, related_name="affidavit_comments"
    )
    comments = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="affidavit_created_by"
    )
    updated_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="affidavit_updated_by"
    )
    
    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.affidavit} {self.comment[:20]}"

app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1">
    <title>Transport Secretary</title>
    <script src="https://code.jquery.com/jquery-3.7.1.slim.js"
        integrity="sha256-UgvvN8vBkgO0luPSUl2s8TIlOSYRoGFAX4jlCIm9Adc="
        crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $('#id_request_type').select2();
            $('.app-btn').addClass('btn btn-sm btn-dark px-5');
        });
    </script>
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
        crossorigin="anonymous">
    <link rel="preconnect"
        href="https://fonts.googleapis.com">
    <link rel="preconnect"
        href="https://fonts.gstatic.com"
        crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet">
    <link rel="shortcut icon"
        href="{% static 'img/favicon.ico' %}"
        type="image/x-icon">
    <style>
        body {
            font-family: 'Montserrat', sans-serif;
        }
    </style>
</head>

<body class="small text-white"
    style="background-color: rgb(36, 98, 164);">
    {% include 'nav.html' %}
    {% include 'messages.html' %}

    <div class="container-fluid min-vh-100">
        {% block content %}
        {% endblock content %}
    </div>
    {% include 'footer.html' %}


    <script
        src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/footer.html
<br>
<div class="small text-bg-dark">
    <div class="container small">
        <footer class="py-3">
            <div class="row small">
                <div class="col-6 col-md-2 mb-1">
                    <h5>Digigov</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a
                                href="https://int.digigov.govt.lc/mot/"
                                target="_blank"
                                class="nav-link p-0 text-white">MOT</a>
                        </li>
                        <li class="nav-item mb-2"><a
                                href="https://digigov.govt.lc/helpdesk/"
                                target="_blank"
                                class="nav-link p-0 text-white">Helpdesk</a>
                        </li>
                        <li class="nav-item mb-2"><a
                                href="https://digigov.govt.lc"
                                target="_blank"
                                class="nav-link p-0 text-white">Service
                                Bureau</a>
                        </li>
                    </ul>
                </div>

                <div class="col-6 col-md-2 mb-3">
                    <h5>Useful links</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a
                                href="http://complaints.dipt.lc"
                                target="_blank"
                                class="nav-link p-0 text-white">Complaints (DIPT)
                                </a>
                        </li>
                        <li class="nav-item mb-2"><a
                                href="http://receipts.goslnet.gov.lc/receipts/"
                                target="_blank"
                                class="nav-link p-0 text-white">Receipts
                                (RIMS)</a>
                        </li>
                        <li class="nav-item mb-2"><a
                                href="https://mail.govt.lc/"
                                target="_blank"
                                class="nav-link p-0 text-white">e-mail
                                (Zimbra)</a>
                        </li>
                    </ul>
                </div>

                <div class="col-6 col-md-2 mb-3">
                    <h5>Contact us</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="tel:17584684342"
                                class="nav-link p-0 text-white">468-4342</a>
                        </li>
                        <li class="nav-item mb-2"><a
                                href="mailto:ict.infrastructure@govt.lc"
                                class="nav-link p-0 text-white">ict.infrastructure@govt.lc</a>
                        </li>
                    </ul>
                </div>
                <!-- 
                <div class="col-md-5 offset-md-1 mb-3">
                    <form>
                        <h5>Subscribe to our newsletter</h5>
                        <p>Monthly digest of what's new and exciting from us.
                        </p>
                        <div
                            class="d-flex flex-column flex-sm-row w-100 gap-2">
                            <label for="newsletter1"
                                class="visually-hidden">Email address</label>
                            <input id="newsletter1"
                                type="text"
                                class="form-control"
                                placeholder="Email address">
                            <button class="btn btn-primary"
                                type="button">Subscribe</button>
                        </div>
                    </form>
                </div> -->
            </div>

            <div
                class="d-flex flex-column flex-sm-row justify-content-between py-1 my-1 border-top">
                <p>&copy; {% now "Y" %} <a class="text-white"
                        href="http://kingship.info"
                        target="_blank">kingship</a>. All rights reserved.</p>
                <!-- <ul class="list-unstyled d-flex">
                    <li class="ms-3"><a class="link-body-emphasis"
                            href="#"><svg class="bi"
                                width="24"
                                height="24">
                                <use xlink:href="#twitter" />
                            </svg></a></li>
                    <li class="ms-3"><a class="link-body-emphasis"
                            href="#"><svg class="bi"
                                width="24"
                                height="24">
                                <use xlink:href="#instagram" />
                            </svg></a></li>
                    <li class="ms-3"><a class="link-body-emphasis"
                            href="#"><svg class="bi"
                                width="24"
                                height="24">
                                <use xlink:href="#facebook" />
                            </svg></a></li>
                </ul> -->
            </div>
        </footer>
    </div>
</div>

app/templates/messages.html
{% if messages %}
<ul class="col-lg-3 mx-auto list-unstyled z-3">
    {% for message in messages %}
    <li {% if message.tags %} class="alert alert-info {{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

app/templates/nav.html
<nav class="py-3 navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        {% if request.user.is_authenticated %}
        <a class="text-decoration-none text-white fw-bold"
            href="{% url 'home' %}">Home</a>

        <a class="text-decoration-none text-white fw-bold"
            href="{% url 'logout' %}">Logout</a>
        {% else %}
        <a class="text-decoration-none text-white fw-bold"
            href="{% url 'exemption-list' %}">Exemptions</a>
        <a class="text-decoration-none text-white fw-bold"
            href="{% url 'hplate-list' %}">H Plate</a>
        <a class="text-decoration-none text-white fw-bold"
            href="{% url 'login' %}">Login</a>
        {% endif %}

    </div>
</nav>
{% if request.user.is_authenticated %}
<div class="d-flex justify-content-center gap-3 pt-2">
    <a class="text-white"
        href="{% url 'affidavits-list' %}">Affidavits</a>
    <a class="text-white"
        href="{% url 'exemption-list' %}">Exemptions</a>
    <a class="text-white"
        href="{% url 'hplate-list' %}">H Plate</a>
    <a class="text-white"
        href="{% url 'book-records-list' %}">Book Records</a>

    {% if request.user.can_register_user %}
    <a class="text-white"
        href="{% url 'register' %}">Register</a>
    {% endif %}


    <a class="ms-5 text-warning"
        href="{% url 'download_file' %}">Update database</a>
</div>
{% endif %}
<br>